#
# Copyright (c) 2024 by Laza Medical.
# All Rights Reserved.
#
---
analyzers:
  ros__parameters:
    path: Supervisor
    monitor:
      type: diagnostic_aggregator/GenericAnalyzer
      path: WatchdogMonitor
      contains: ['WatchdogMonitor']
    heartbeat:
      type: diagnostic_aggregator/GenericAnalyzer
      path: Heartbeats
      contains: ['heartbeat']
