name: CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-24.04 ]
        ros_distribution: [ jazzy ]
    steps:
    - uses: actions/checkout@v2
    - uses: ros-tooling/setup-ros@0.7.9
      with:
        required-ros-distributions: ${{ matrix.ros_distribution }}
    - uses : ros-tooling/action-ros-ci@0.3.14
      with:
        package-name: "sw_watchdog"
        target-ros2-distro: ${{ matrix.ros_distribution }}
        vcs-repo-file-url: ""
        colcon-mixin-name: coverage-gcc
        colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml
    - uses: codecov/codecov-action@v1
      with:
        file: ros_ws/lcov/total_coverage.info
